FROM tiangolo/uvicorn-gunicorn-fastapi:python3.8-alpine3.10
RUN pip install --upgrade pip \
    && pip install aiofiles \
    && rm -rf ~/.cache/pip/*
COPY static /app/static
COPY backend_vrs_db.py /app/
COPY backend_fastapi.py /app/main.py
