name: flightmap
channels:
  - conda-forge
dependencies:
  - python=3
  - gdal
  - shapely
  - gunicorn
  - uvloop
  - requests
  - redis-py
  - pandas
  - nodejs
  - pip
  - pip:
    - geojson
    - fastapi
    - uvicorn
    - aiofiles
    - httptools
    - pyopensky
    - sqlalchemy

